//
// This file is autogenerated
//

//
//  AccountRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Account
//

public class AccountRequest: Request {

/*!
 Change the passphrase from old to new. If old isn't set, and force is false,
 then prompt at the UI for it. If old isn't set and force is true, then we'll
 try to force a passphrase change.
 */
  public func passphraseChange(oldPassphrase: String, passphrase: String, force: Bool) throws {
    let args: [String: Any] = ["oldPassphrase": oldPassphrase, "passphrase": passphrase, "force": force]
    _ = try self.sendRequest(method: "keybase.1.account.passphraseChange", args: args)
  }

  public func passphrasePrompt(guiArg: GUIEntryArg) throws -> GetPassphraseRes {
    let args: [String: Any] = ["guiArg": guiArg]
    let response = try self.sendRequest(method: "keybase.1.account.passphrasePrompt", args: args)
    try checkNull(response: response)
    return GetPassphraseRes.fromJSON(JSON(response))
  }

/*!
 * change email to the new given email by signing a statement.
 */
  public func emailChange(newEmail: String) throws {
    let args: [String: Any] = ["newEmail": newEmail]
    _ = try self.sendRequest(method: "keybase.1.account.emailChange", args: args)
  }

/*!
 * Whether the logged-in user has uploaded private keys
 * Will error if not logged in.
 */
  public func hasServerKeys() throws -> HasServerKeysRes {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.account.hasServerKeys", args: args)
    try checkNull(response: response)
    return HasServerKeysRes.fromJSON(JSON(response))
  }

}
