//
// This file is autogenerated
//

//
//  Account.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Account
//


public class HasServerKeysRes {

	public let hasServerKeys: Bool?

  public init(hasServerKeys: Bool) {
    self.hasServerKeys = hasServerKeys
  }

  public class func fromJSON(_ json: JSON) -> HasServerKeysRes {
    return HasServerKeysRes(hasServerKeys: json["hasServerKeys"].boolValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [HasServerKeysRes] {
    return json.map { fromJSON($0) }
  }

}

