//
// This file is autogenerated
//

//
//  Account.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Account
//


public class Feature {

	public let allow: Bool
	public let defaultValue: Bool
	public let readonly: Bool
	public let label: String

  public init(allow: Bool, defaultValue: Bool, readonly: Bool, label: String) {
    self.allow = allow
		self.defaultValue = defaultValue
		self.readonly = readonly
		self.label = label
  }

  public class func fromJSON(json: JSON) -> Feature {
    return Feature(allow: json["allow"].boolValue, defaultValue: json["defaultValue"].boolValue, readonly: json["readonly"].boolValue, label: json["label"].stringValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [Feature] {
    return json.map { fromJSON($0) }
  }
}


public class GUIEntryFeatures {

	public let storeSecret: Feature
	public let showTyping: Feature

  public init(storeSecret: Feature, showTyping: Feature) {
    self.storeSecret = storeSecret
		self.showTyping = showTyping
  }

  public class func fromJSON(json: JSON) -> GUIEntryFeatures {
    return GUIEntryFeatures(storeSecret: Feature.fromJSON(json["storeSecret"]), showTyping: Feature.fromJSON(json["showTyping"]))
  }

  public class func fromJSONArray(json: [JSON]) -> [GUIEntryFeatures] {
    return json.map { fromJSON($0) }
  }
}

public enum PassphraseType: Int {
	case None = 0
	case PaperKey = 1
	case PassPhrase = 2
	case VerifyPassPhrase = 3
}


public class GUIEntryArg {

	public let windowTitle: String
	public let prompt: String
	public let username: String
	public let submitLabel: String
	public let cancelLabel: String
	public let retryLabel: String
	public let type: PassphraseType
	public let features: GUIEntryFeatures

  public init(windowTitle: String, prompt: String, username: String, submitLabel: String, cancelLabel: String, retryLabel: String, type: PassphraseType, features: GUIEntryFeatures) {
    self.windowTitle = windowTitle
		self.prompt = prompt
		self.username = username
		self.submitLabel = submitLabel
		self.cancelLabel = cancelLabel
		self.retryLabel = retryLabel
		self.type = type
		self.features = features
  }

  public class func fromJSON(json: JSON) -> GUIEntryArg {
    return GUIEntryArg(windowTitle: json["windowTitle"].stringValue, prompt: json["prompt"].stringValue, username: json["username"].stringValue, submitLabel: json["submitLabel"].stringValue, cancelLabel: json["cancelLabel"].stringValue, retryLabel: json["retryLabel"].stringValue, type: PassphraseType(rawValue: json["type"].intValue)!, features: GUIEntryFeatures.fromJSON(json["features"]))
  }

  public class func fromJSONArray(json: [JSON]) -> [GUIEntryArg] {
    return json.map { fromJSON($0) }
  }
}


public class GetPassphraseRes {

	public let passphrase: String
	public let storeSecret: Bool

  public init(passphrase: String, storeSecret: Bool) {
    self.passphrase = passphrase
		self.storeSecret = storeSecret
  }

  public class func fromJSON(json: JSON) -> GetPassphraseRes {
    return GetPassphraseRes(passphrase: json["passphrase"].stringValue, storeSecret: json["storeSecret"].boolValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [GetPassphraseRes] {
    return json.map { fromJSON($0) }
  }
}
