//
// This file is autogenerated
//

//
//  ApiserverRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Apiserver
//

public class ApiserverRequest: Request {

  public func get(endpoint: String, args: [StringKVPair], httpStatus: [Int], appStatusCode: [Int]) throws -> APIRes {
    let args: [String: Any] = ["endpoint": endpoint, "args": args, "httpStatus": httpStatus, "appStatusCode": appStatusCode]
    let response = try self.sendRequest(method: "keybase.1.apiserver.Get", args: args)
    try checkNull(response: response)
    return APIRes.fromJSON(JSON(response))
  }

  public func post(endpoint: String, args: [StringKVPair], httpStatus: [Int], appStatusCode: [Int]) throws -> APIRes {
    let args: [String: Any] = ["endpoint": endpoint, "args": args, "httpStatus": httpStatus, "appStatusCode": appStatusCode]
    let response = try self.sendRequest(method: "keybase.1.apiserver.Post", args: args)
    try checkNull(response: response)
    return APIRes.fromJSON(JSON(response))
  }

  public func postJSON(endpoint: String, args: [StringKVPair], JSONPayload: [StringKVPair], httpStatus: [Int], appStatusCode: [Int]) throws -> APIRes {
    let args: [String: Any] = ["endpoint": endpoint, "args": args, "JSONPayload": JSONPayload, "httpStatus": httpStatus, "appStatusCode": appStatusCode]
    let response = try self.sendRequest(method: "keybase.1.apiserver.PostJSON", args: args)
    try checkNull(response: response)
    return APIRes.fromJSON(JSON(response))
  }

}
