//
// This file is autogenerated
//

//
//  BackendCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// BackendCommon
//

public class BackendCommonRequest: Request {

}
