//
// This file is autogenerated
//

//
//  BackendCommon.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// BackendCommon
//


public class BlockIdCombo {

	public let blockHash: String?
	public let chargedTo: String?

  public init(blockHash: String, chargedTo: String) {
    self.blockHash = blockHash
		self.chargedTo = chargedTo
  }

  public class func fromJSON(_ json: JSON) -> BlockIdCombo {
    return BlockIdCombo(blockHash: json["blockHash"].stringValue, chargedTo: json["chargedTo"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [BlockIdCombo] {
    return json.map { fromJSON($0) }
  }

}



public class ChallengeInfo {

	public let now: Int64?
	public let challenge: String?

  public init(now: Int64, challenge: String) {
    self.now = now
		self.challenge = challenge
  }

  public class func fromJSON(_ json: JSON) -> ChallengeInfo {
    return ChallengeInfo(now: json["now"].int64Value, challenge: json["challenge"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [ChallengeInfo] {
    return json.map { fromJSON($0) }
  }

}

