//
// This file is autogenerated
//

//
//  BTCRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// BTC
//

public class BTCRequest: Request {

  public func registerBTC(address: String, force: Bool) throws {
    let args: [String: Any] = ["address": address, "force": force]
    _ = try self.sendRequest(method: "keybase.1.BTC.registerBTC", args: args)
  }

}
