//
// This file is autogenerated
//

//
//  CommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Common
//

public class CommonRequest: Request {

}
