//
// This file is autogenerated
//

//
//  ConfigRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Config
//

public class ConfigRequest: Request {

  public func getCurrentStatus() throws -> GetCurrentStatusRes {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.config.getCurrentStatus", args: args)
    try checkNull(response)
    return GetCurrentStatusRes.fromJSON(JSON(response))
  }

  public func getExtendedStatus() throws -> ExtendedStatus {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.config.getExtendedStatus", args: args)
    try checkNull(response)
    return ExtendedStatus.fromJSON(JSON(response))
  }

  public func getConfig() throws -> Config {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.config.getConfig", args: args)
    try checkNull(response)
    return Config.fromJSON(JSON(response))
  }

/*!
 Change user config.
 For example, to update primary picture source:
 key=picture.source, value=twitter (or github)
 */
  public func setUserConfig(username: String, key: String, value: String) throws {
    let args: [String: AnyObject] = ["username": username, "key": key, "value": value]
    try self.sendRequest("keybase.1.config.setUserConfig", args: args)
  }

  public func setPath(path: String) throws {
    let args: [String: AnyObject] = ["path": path]
    try self.sendRequest("keybase.1.config.setPath", args: args)
  }

  public func helloIAm(details: ClientDetails) throws {
    let args: [String: AnyObject] = ["details": details]
    try self.sendRequest("keybase.1.config.helloIAm", args: args)
  }

  public func setValue(path: String, value: ConfigValue) throws {
    let args: [String: AnyObject] = ["path": path, "value": value]
    try self.sendRequest("keybase.1.config.setValue", args: args)
  }

  public func clearValue(path: String) throws {
    let args: [String: AnyObject] = ["path": path]
    try self.sendRequest("keybase.1.config.clearValue", args: args)
  }

  public func getValue(path: String) throws -> ConfigValue {
    let args: [String: AnyObject] = ["path": path]
    let response = try self.sendRequest("keybase.1.config.getValue", args: args)
    try checkNull(response)
    return ConfigValue.fromJSON(JSON(response))
  }

}
