//
// This file is autogenerated
//

//
//  Constants.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Constants
//

public enum StatusCode: Int {
	case scok = 0
	case scinputerror = 100
	case scloginrequired = 201
	case scbadsession = 202
	case scbadloginusernotfound = 203
	case scbadloginpassword = 204
	case scnotfound = 205
	case scthrottlecontrol = 210
	case scdeleted = 216
	case scgeneric = 218
	case scalreadyloggedin = 235
	case scexists = 230
	case sccanceled = 237
	case scinputcanceled = 239
	case screloginrequired = 274
	case scresolutionfailed = 275
	case scprofilenotpublic = 276
	case scidentifyfailed = 277
	case sctrackingbroke = 278
	case scwrongcryptoformat = 279
	case scdecryptionerror = 280
	case scinvalidaddress = 281
	case scbademail = 472
	case scbadsignupusernametaken = 701
	case scbadinvitationcode = 707
	case scmissingresult = 801
	case sckeynotfound = 901
	case sckeyinuse = 907
	case sckeybadgen = 913
	case sckeynosecret = 914
	case sckeybaduids = 915
	case sckeynoactive = 916
	case sckeynosig = 917
	case sckeybadsig = 918
	case sckeybadeldest = 919
	case sckeynoeldest = 920
	case sckeyduplicateupdate = 921
	case scsibkeyalreadyexists = 922
	case scdecryptionkeynotfound = 924
	case sckeynopgpencryption = 927
	case sckeynonaclencryption = 928
	case sckeysyncedpgpnotfound = 929
	case sckeynomatchinggpg = 930
	case sckeyrevoked = 931
	case scbadtracksession = 1301
	case scdevicebadname = 1404
	case scdevicenameinuse = 1408
	case scdevicenotfound = 1409
	case scdevicemismatch = 1410
	case scdevicerequired = 1411
	case scdeviceprevprovisioned = 1413
	case scdevicenoprovision = 1414
	case scstreamexists = 1501
	case scstreamnotfound = 1502
	case scstreamwrongkind = 1503
	case scstreameof = 1504
	case scgenericapierror = 1600
	case scapinetworkerror = 1601
	case sctimeout = 1602
	case scprooferror = 1701
	case scidentificationexpired = 1702
	case scselfnotfound = 1703
	case scbadkexphrase = 1704
	case scnouidelegation = 1705
	case scnoui = 1706
	case scgpgunavailable = 1707
	case scinvalidversionerror = 1800
	case scoldversionerror = 1801
	case scinvalidlocationerror = 1802
	case scservicestatuserror = 1803
	case scinstallerror = 1804
	case scchatinternal = 2500
	case scchatratelimit = 2501
	case scchatconvexists = 2502
	case scchatunknowntlfid = 2503
	case scchatnotinconv = 2504
	case scchatbadmsg = 2505
	case scchatbroadcast = 2506
	case scchatalreadysuperseded = 2507
	case scchatalreadydeleted = 2508
	case scchattlffinalized = 2509
	case scchatcollision = 2510
}
