//
// This file is autogenerated
//

//
//  ConstantsRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Constants
//

public class ConstantsRequest: Request {

}
