//
// This file is autogenerated
//

//
//  CryptocurrencyRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Cryptocurrency
//

public class CryptocurrencyRequest: Request {

  public func registerAddress(address: String, force: Bool, wantedFamily: String) throws -> RegisterAddressRes {
    let args: [String: Any] = ["address": address, "force": force, "wantedFamily": wantedFamily]
    let response = try self.sendRequest(method: "keybase.1.cryptocurrency.registerAddress", args: args)
    try checkNull(response: response)
    return RegisterAddressRes.fromJSON(JSON(response))
  }

}
