//
// This file is autogenerated
//

//
//  Cryptocurrency.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Cryptocurrency
//


public class RegisterAddressRes {

	public let type: String?
	public let family: String?

  public init(type: String, family: String) {
    self.type = type
		self.family = family
  }

  public class func fromJSON(_ json: JSON) -> RegisterAddressRes {
    return RegisterAddressRes(type: json["type"].stringValue, family: json["family"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [RegisterAddressRes] {
    return json.map { fromJSON($0) }
  }

}

