//
// This file is autogenerated
//

//
//  Ctl.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Ctl
//

public enum ExitCode: Int {
	case Ok = 0
	case Notok = 2
	case Restart = 4
}
