//
// This file is autogenerated
//

//
//  Ctl.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Ctl
//

public enum ExitCode: Int {
	case ok = 0
	case notok = 2
	case restart = 4
}
