//
// This file is autogenerated
//

//
//  CtlRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Ctl
//

public class CtlRequest: Request {

  public func stop(exitCode: ExitCode) throws {
    let args: [String: AnyObject] = ["exitCode": exitCode.rawValue]
    try self.sendRequest("keybase.1.ctl.stop", args: args)
  }

  public func logRotate() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.ctl.logRotate", args: args)
  }

  public func reload() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.ctl.reload", args: args)
  }

  public func dbNuke() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.ctl.dbNuke", args: args)
  }

}
