//
// This file is autogenerated
//

//
//  Debugging.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Debugging
//


public class FirstStepResult {

	public let valPlusTwo: Int?

  public init(valPlusTwo: Int) {
    self.valPlusTwo = valPlusTwo
  }

  public class func fromJSON(_ json: JSON) -> FirstStepResult {
    return FirstStepResult(valPlusTwo: json["valPlusTwo"].intValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [FirstStepResult] {
    return json.map { fromJSON($0) }
  }

}

