//
// This file is autogenerated
//

//
//  DeviceRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Device
//

public class DeviceRequest: Request {

/*!
 List devices for the user.
 */
  public func deviceList() throws -> [Device] {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.device.deviceList", args: args)
  try checkNull(response)
  return Device.fromJSONArray(JSON(response).arrayValue)
  }

/*!
 Starts the process of adding a new device using an existing
 device. It is called on the existing device. 
 This is for kex2.
 */
  public func deviceAdd() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.device.deviceAdd", args: args)
  }

/*!
 Checks the device name format.
 */
  public func checkDeviceNameFormat(name: String) throws -> Bool {
    let args: [String: AnyObject] = ["name": name]
    let response = try self.sendRequest("keybase.1.device.checkDeviceNameFormat", args: args)
    try checkNull(response)
    return JSON(response).boolValue
  }

}
