//
// This file is autogenerated
//

//
//  FavoriteRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Favorite
//

public class FavoriteRequest: Request {

/*!
 Adds a folder to a user's list of favorite folders.
 */
  public func favoriteAdd(folder: Folder) throws {
    let args: [String: Any] = ["folder": folder]
    _ = try self.sendRequest(method: "keybase.1.favorite.favoriteAdd", args: args)
  }

/*!
 Removes a folder from a user's list of favorite folders.
 */
  public func favoriteIgnore(folder: Folder) throws {
    let args: [String: Any] = ["folder": folder]
    _ = try self.sendRequest(method: "keybase.1.favorite.favoriteIgnore", args: args)
  }

/*!
 Returns all of a user's favorite folders.
 */
  public func getFavorites() throws -> FavoritesResult {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.favorite.getFavorites", args: args)
    try checkNull(response: response)
    return FavoritesResult.fromJSON(JSON(response))
  }

}
