//
// This file is autogenerated
//

//
//  Favorite.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Favorite
//


public class Folder {

	public let name: String
	public let isPrivate: Bool
	public let notificationsOn: Bool

  public init(name: String, isPrivate: Bool, notificationsOn: Bool) {
    self.name = name
		self.isPrivate = isPrivate
		self.notificationsOn = notificationsOn
  }

  public class func fromJSON(json: JSON) -> Folder {
    return Folder(name: json["name"].stringValue, isPrivate: json["isPrivate"].boolValue, notificationsOn: json["notificationsOn"].boolValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [Folder] {
    return json.map { fromJSON($0) }
  }
}
