//
// This file is autogenerated
//

//
//  Fs.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Fs
//


public class File {

	public let path: String?

  public init(path: String) {
    self.path = path
  }

  public class func fromJSON(_ json: JSON) -> File {
    return File(path: json["path"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [File] {
    return json.map { fromJSON($0) }
  }

}



public class ListResult {

	public let files: [File]?

  public init(files: [File]) {
    self.files = files
  }

  public class func fromJSON(_ json: JSON) -> ListResult {
    return ListResult(files: File.fromJSONArray(json["files"].arrayValue))
  }

  public class func fromJSONArray(_ json: [JSON]) -> [ListResult] {
    return json.map { fromJSON($0) }
  }

}

