//
// This file is autogenerated
//

//
//  GpgCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// GpgCommon
//

public class GpgCommonRequest: Request {

}
