//
// This file is autogenerated
//

//
//  GpgUIRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// GpgUI
//

public class GpgUIRequest: Request {

  public func wantToAddGPGKey() throws -> Bool {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.gpgUi.wantToAddGPGKey", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func confirmDuplicateKeyChosen() throws -> Bool {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.gpgUi.confirmDuplicateKeyChosen", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func selectKeyAndPushOption(keys: [GPGKey]) throws -> SelectKeyRes {
    let args: [String: Any] = ["keys": keys]
    let response = try self.sendRequest(method: "keybase.1.gpgUi.selectKeyAndPushOption", args: args)
    try checkNull(response: response)
    return SelectKeyRes.fromJSON(JSON(response))
  }

  public func selectKey(keys: [GPGKey]) throws -> String {
    let args: [String: Any] = ["keys": keys]
    let response = try self.sendRequest(method: "keybase.1.gpgUi.selectKey", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

  public func sign(msg: NSData, fingerprint: NSData) throws -> String {
    let args: [String: Any] = ["msg": msg, "fingerprint": fingerprint]
    let response = try self.sendRequest(method: "keybase.1.gpgUi.sign", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

  public func getTTY() throws -> String {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.gpgUi.getTTY", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

}
