//
// This file is autogenerated
//

//
//  GpgUI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// GpgUI
//


public class SelectKeyRes {

	public let keyID: String?
	public let doSecretPush: Bool?

  public init(keyID: String, doSecretPush: Bool) {
    self.keyID = keyID
		self.doSecretPush = doSecretPush
  }

  public class func fromJSON(_ json: JSON) -> SelectKeyRes {
    return SelectKeyRes(keyID: json["keyID"].stringValue, doSecretPush: json["doSecretPush"].boolValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [SelectKeyRes] {
    return json.map { fromJSON($0) }
  }

}

