//
// This file is autogenerated
//

//
//  GpgUi.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// GpgUi
//


public class GPGKey {

	public let algorithm: String
	public let keyID: String
	public let creation: String
	public let expiration: String
	public let identities: [PGPIdentity]

  public init(algorithm: String, keyID: String, creation: String, expiration: String, identities: [PGPIdentity]) {
    self.algorithm = algorithm
		self.keyID = keyID
		self.creation = creation
		self.expiration = expiration
		self.identities = identities
  }

  public class func fromJSON(json: JSON) -> GPGKey {
    return GPGKey(algorithm: json["algorithm"].stringValue, keyID: json["keyID"].stringValue, creation: json["creation"].stringValue, expiration: json["expiration"].stringValue, identities: PGPIdentity.fromJSONArray(json["identities"].arrayValue))
  }

  public class func fromJSONArray(json: [JSON]) -> [GPGKey] {
    return json.map { fromJSON($0) }
  }
}


public class SelectKeyRes {

	public let keyID: String
	public let doSecretPush: Bool

  public init(keyID: String, doSecretPush: Bool) {
    self.keyID = keyID
		self.doSecretPush = doSecretPush
  }

  public class func fromJSON(json: JSON) -> SelectKeyRes {
    return SelectKeyRes(keyID: json["keyID"].stringValue, doSecretPush: json["doSecretPush"].boolValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [SelectKeyRes] {
    return json.map { fromJSON($0) }
  }
}
