//
// This file is autogenerated
//

//
//  IdentifyCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// IdentifyCommon
//

public class IdentifyCommonRequest: Request {

}
