//
// This file is autogenerated
//

//
//  InstallRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Install
//

public class InstallRequest: Request {

}
