//
// This file is autogenerated
//

//
//  KbfsMountRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// KbfsMount
//

public class KbfsMountRequest: Request {

  public func getCurrentMountDir() throws -> String {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.kbfsMount.GetCurrentMountDir", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

  public func getAllAvailableMountDirs() throws -> [String] {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.kbfsMount.GetAllAvailableMountDirs", args: args)
  try checkNull(response: response)
  return String.fromJSONArray(JSON(response).arrayValue)
  }

  public func setCurrentMountDir(dir: String) throws {
    let args: [String: Any] = ["dir": dir]
    _ = try self.sendRequest(method: "keybase.1.kbfsMount.SetCurrentMountDir", args: args)
  }

}
