//
// This file is autogenerated
//

//
//  KbfsRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kbfs
//

public class KbfsRequest: Request {

/*!
 Idea is that kbfs would call the function below whenever these actions are
 performed on a file.

 Note that this list/interface is very temporary and highly likely to change
 significantly.

 It is just a starting point to get kbfs notifications through the daemon to
 the clients.
 */
  public func fSEvent(event: FSNotification) throws {
    let args: [String: AnyObject] = ["event": event]
    try self.sendRequest("keybase.1.kbfs.FSEvent", args: args)
  }

}
