//
// This file is autogenerated
//

//
//  KbfsCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// KbfsCommon
//

public class KbfsCommonRequest: Request {

}
