//
// This file is autogenerated
//

//
//  Kex2ProvisionerRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kex2Provisioner
//

public class Kex2ProvisionerRequest: Request {

  public func kexStart() throws {
    let args: [String: Any] = [String: Any]()
    _ = try self.sendRequest(method: "keybase.1.Kex2Provisioner.kexStart", args: args)
  }

}
