//
// This file is autogenerated
//

//
//  Kex2Provisionee2.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kex2Provisionee2
//


public class Hello2Res {

	public let encryptionKey: String?
	public let sigPayload: String?

  public init(encryptionKey: String, sigPayload: String) {
    self.encryptionKey = encryptionKey
		self.sigPayload = sigPayload
  }

  public class func fromJSON(_ json: JSON) -> Hello2Res {
    return Hello2Res(encryptionKey: json["encryptionKey"].stringValue, sigPayload: json["sigPayload"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [Hello2Res] {
    return json.map { fromJSON($0) }
  }

}

