//
// This file is autogenerated
//

//
//  Kex2ProvisioneeRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kex2Provisionee
//

public class Kex2ProvisioneeRequest: Request {

  public func hello(uid: String, token: String, csrf: String, pps: PassphraseStream, sigBody: String) throws -> String {
    let args: [String: AnyObject] = ["uid": uid, "token": token, "csrf": csrf, "pps": pps, "sigBody": sigBody]
    let response = try self.sendRequest("keybase.1.Kex2Provisionee.hello", args: args)
    try checkNull(response)
    return JSON(response).stringValue
  }

  public func didCounterSign(sig: NSData) throws {
    let args: [String: AnyObject] = ["sig": sig]
    try self.sendRequest("keybase.1.Kex2Provisionee.didCounterSign", args: args)
  }

}
