//
// This file is autogenerated
//

//
//  Kex2Provisionee2Request.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kex2Provisionee2
//

public class Kex2Provisionee2Request: Request {

  public func hello2(uid: String, token: String, csrf: String, sigBody: String) throws -> Hello2Res {
    let args: [String: Any] = ["uid": uid, "token": token, "csrf": csrf, "sigBody": sigBody]
    let response = try self.sendRequest(method: "keybase.1.Kex2Provisionee2.hello2", args: args)
    try checkNull(response: response)
    return Hello2Res.fromJSON(JSON(response))
  }

  public func didCounterSign2(sig: NSData, ppsEncrypted: String) throws {
    let args: [String: Any] = ["sig": sig, "ppsEncrypted": ppsEncrypted]
    _ = try self.sendRequest(method: "keybase.1.Kex2Provisionee2.didCounterSign2", args: args)
  }

}
