//
// This file is autogenerated
//

//
//  Kex2ProvisionerRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Kex2Provisioner
//

public class Kex2ProvisionerRequest: Request {

  public func kexStart() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.Kex2Provisioner.kexStart", args: args)
  }

}
