//
// This file is autogenerated
//

//
//  LoginUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// LoginUi
//

public class LoginUiRequest: Request {

  public func getEmailOrUsername() throws -> String {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.loginUi.getEmailOrUsername", args: args)
    try checkNull(response)
    return JSON(response).stringValue
  }

  public func promptRevokePaperKeys(device: Device, index: Int) throws -> Bool {
    let args: [String: AnyObject] = ["device": device, "index": NSNumber(integer: index)]
    let response = try self.sendRequest("keybase.1.loginUi.promptRevokePaperKeys", args: args)
    try checkNull(response)
    return JSON(response).boolValue
  }

  public func displayPaperKeyPhrase(phrase: String) throws {
    let args: [String: AnyObject] = ["phrase": phrase]
    try self.sendRequest("keybase.1.loginUi.displayPaperKeyPhrase", args: args)
  }

  public func displayPrimaryPaperKey(phrase: String) throws {
    let args: [String: AnyObject] = ["phrase": phrase]
    try self.sendRequest("keybase.1.loginUi.displayPrimaryPaperKey", args: args)
  }

}
