//
// This file is autogenerated
//

//
//  LogUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// LogUi
//

public class LogUiRequest: Request {

  public func log(level: LogLevel, text: Text) throws {
    let args: [String: AnyObject] = ["level": level.rawValue, "text": text]
    try self.sendRequest("keybase.1.logUi.log", args: args)
  }

}
