//
// This file is autogenerated
//

//
//  LogUIRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// LogUI
//

public class LogUIRequest: Request {

  public func log(level: LogLevel, text: Text) throws {
    let args: [String: Any] = ["level": level.rawValue, "text": text]
    _ = try self.sendRequest(method: "keybase.1.logUi.log", args: args)
  }

}
