//
// This file is autogenerated
//

//
//  MetadataUpdateRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// MetadataUpdate
//

public class MetadataUpdateRequest: Request {

  public func metadataUpdate(folderID: String, revision: Int64) throws {
    let args: [String: Any] = ["folderID": folderID, "revision": NSNumber(value: revision)]
    _ = try self.sendRequest(method: "keybase.1.metadataUpdate.metadataUpdate", args: args)
  }

  public func folderNeedsRekey(folderID: String, revision: Int64) throws {
    let args: [String: Any] = ["folderID": folderID, "revision": NSNumber(value: revision)]
    _ = try self.sendRequest(method: "keybase.1.metadataUpdate.folderNeedsRekey", args: args)
  }

}
