//
// This file is autogenerated
//

//
//  NotifyCtl.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyCtl
//


public class NotificationChannels {

	public let session: Bool
	public let users: Bool
	public let kbfs: Bool
	public let tracking: Bool

  public init(session: Bool, users: Bool, kbfs: Bool, tracking: Bool) {
    self.session = session
		self.users = users
		self.kbfs = kbfs
		self.tracking = tracking
  }

  public class func fromJSON(json: JSON) -> NotificationChannels {
    return NotificationChannels(session: json["session"].boolValue, users: json["users"].boolValue, kbfs: json["kbfs"].boolValue, tracking: json["tracking"].boolValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [NotificationChannels] {
    return json.map { fromJSON($0) }
  }
}
