//
// This file is autogenerated
//

//
//  NotifyKeyfamilyRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyKeyfamily
//

public class NotifyKeyfamilyRequest: Request {

  public func keyfamilyChanged(uid: String) throws {
    let args: [String: Any] = ["uid": uid]
    _ = try self.sendRequest(method: "keybase.1.NotifyKeyfamily.keyfamilyChanged", args: args)
  }

}
