//
// This file is autogenerated
//

//
//  NotifyUsersRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyUsers
//

public class NotifyUsersRequest: Request {

  public func userChanged(uid: String) throws {
    let args: [String: Any] = ["uid": uid]
    _ = try self.sendRequest(method: "keybase.1.NotifyUsers.userChanged", args: args)
  }

}
