//
// This file is autogenerated
//

//
//  NotifyUsersRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyUsers
//

public class NotifyUsersRequest: Request {

  public func userChanged(uid: String) throws {
    let args: [String: AnyObject] = ["uid": uid]
    try self.sendRequest("keybase.1.NotifyUsers.userChanged", args: args)
  }

}
