//
// This file is autogenerated
//

//
//  NotifyFavoritesRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyFavorites
//

public class NotifyFavoritesRequest: Request {

  public func favoritesChanged(uid: String) throws {
    let args: [String: Any] = ["uid": uid]
    _ = try self.sendRequest(method: "keybase.1.NotifyFavorites.favoritesChanged", args: args)
  }

}
