//
// This file is autogenerated
//

//
//  NotifyFSRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyFS
//

public class NotifyFSRequest: Request {

  public func fSActivity(notification: FSNotification) throws {
    let args: [String: AnyObject] = ["notification": notification]
    try self.sendRequest("keybase.1.NotifyFS.FSActivity", args: args)
  }

}
