//
// This file is autogenerated
//

//
//  NotifyBadgesRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyBadges
//

public class NotifyBadgesRequest: Request {

  public func badgeState(badgeState: BadgeState) throws {
    let args: [String: Any] = ["badgeState": badgeState]
    _ = try self.sendRequest(method: "keybase.1.NotifyBadges.badgeState", args: args)
  }

}
