//
// This file is autogenerated
//

//
//  NotifyFSRequestRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyFSRequest
//

public class NotifyFSRequestRequest: Request {

  public func fSEditListRequest(req: FSEditListRequest) throws {
    let args: [String: Any] = ["req": req]
    _ = try self.sendRequest(method: "keybase.1.NotifyFSRequest.FSEditListRequest", args: args)
  }

  public func fSSyncStatusRequest(req: FSSyncStatusRequest) throws {
    let args: [String: Any] = ["req": req]
    _ = try self.sendRequest(method: "keybase.1.NotifyFSRequest.FSSyncStatusRequest", args: args)
  }

}
