//
// This file is autogenerated
//

//
//  NotifySessionRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifySession
//

public class NotifySessionRequest: Request {

  public func loggedOut() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.NotifySession.loggedOut", args: args)
  }

  public func loggedIn(username: String) throws {
    let args: [String: AnyObject] = ["username": username]
    try self.sendRequest("keybase.1.NotifySession.loggedIn", args: args)
  }

  public func clientOutOfDate(upgradeTo: String, upgradeURI: String) throws {
    let args: [String: AnyObject] = ["upgradeTo": upgradeTo, "upgradeURI": upgradeURI]
    try self.sendRequest("keybase.1.NotifySession.clientOutOfDate", args: args)
  }

}
