//
// This file is autogenerated
//

//
//  NotifyPaperKeyRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyPaperKey
//

public class NotifyPaperKeyRequest: Request {

  public func paperKeyCached(uid: String, encKID: String, sigKID: String) throws {
    let args: [String: Any] = ["uid": uid, "encKID": encKID, "sigKID": sigKID]
    _ = try self.sendRequest(method: "keybase.1.NotifyPaperKey.paperKeyCached", args: args)
  }

}
