//
// This file is autogenerated
//

//
//  NotifyAppRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyApp
//

public class NotifyAppRequest: Request {

  public func exit() throws {
    let args: [String: Any] = [String: Any]()
    _ = try self.sendRequest(method: "keybase.1.NotifyApp.exit", args: args)
  }

}
