//
// This file is autogenerated
//

//
//  NotifyServiceRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyService
//

public class NotifyServiceRequest: Request {

  public func shutdown() throws {
    let args: [String: Any] = [String: Any]()
    _ = try self.sendRequest(method: "keybase.1.NotifyService.shutdown", args: args)
  }

}
