//
// This file is autogenerated
//

//
//  NotifyTrackingRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyTracking
//

public class NotifyTrackingRequest: Request {

  public func trackingChanged(uid: String, username: String) throws {
    let args: [String: AnyObject] = ["uid": uid, "username": username]
    try self.sendRequest("keybase.1.NotifyTracking.trackingChanged", args: args)
  }

}
