//
// This file is autogenerated
//

//
//  NotifyCtlRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyCtl
//

public class NotifyCtlRequest: Request {

  public func setNotifications(channels: NotificationChannels) throws {
    let args: [String: Any] = ["channels": channels]
    _ = try self.sendRequest(method: "keybase.1.notifyCtl.setNotifications", args: args)
  }

}
