//
// This file is autogenerated
//

//
//  NotifyBadges.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// NotifyBadges
//

public typealias ChatConversationID = NSData

public class BadgeState {

	public let total: Int?
	public let newTlfs: Int?
	public let rekeysNeeded: Int?
	public let newFollowers: Int?
	public let unreadChatMessages: Int?
	public let unreadChatConversations: Int?
	public let conversations: [BadgeConversationInfo]?

  public init(total: Int, newTlfs: Int, rekeysNeeded: Int, newFollowers: Int, unreadChatMessages: Int, unreadChatConversations: Int, conversations: [BadgeConversationInfo]) {
    self.total = total
		self.newTlfs = newTlfs
		self.rekeysNeeded = rekeysNeeded
		self.newFollowers = newFollowers
		self.unreadChatMessages = unreadChatMessages
		self.unreadChatConversations = unreadChatConversations
		self.conversations = conversations
  }

  public class func fromJSON(_ json: JSON) -> BadgeState {
    return BadgeState(total: json["total"].intValue, newTlfs: json["newTlfs"].intValue, rekeysNeeded: json["rekeysNeeded"].intValue, newFollowers: json["newFollowers"].intValue, unreadChatMessages: json["unreadChatMessages"].intValue, unreadChatConversations: json["unreadChatConversations"].intValue, conversations: BadgeConversationInfo.fromJSONArray(json["conversations"].arrayValue))
  }

  public class func fromJSONArray(_ json: [JSON]) -> [BadgeState] {
    return json.map { fromJSON($0) }
  }

}



public class BadgeConversationInfo {

	public let convID: NSData?
	public let UnreadMessages: Int?

  public init(convID: NSData, UnreadMessages: Int) {
    self.convID = convID
		self.UnreadMessages = UnreadMessages
  }

  public class func fromJSON(_ json: JSON) -> BadgeConversationInfo {
    return BadgeConversationInfo(convID: json["convID"].object as! NSData, UnreadMessages: json["UnreadMessages"].intValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [BadgeConversationInfo] {
    return json.map { fromJSON($0) }
  }

}

