//
// This file is autogenerated
//

//
//  PassphraseCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// PassphraseCommon
//

public class PassphraseCommonRequest: Request {

}
