//
// This file is autogenerated
//

//
//  PgpUIRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// PgpUI
//

public class PgpUIRequest: Request {

  public func outputSignatureSuccess(fingerprint: String, username: String, signedAt: Int64) throws {
    let args: [String: Any] = ["fingerprint": fingerprint, "username": username, "signedAt": NSNumber(value: signedAt)]
    _ = try self.sendRequest(method: "keybase.1.pgpUi.outputSignatureSuccess", args: args)
  }

  public func outputSignatureSuccessNonKeybase(keyID: String, signedAt: Int64) throws {
    let args: [String: Any] = ["keyID": keyID, "signedAt": NSNumber(value: signedAt)]
    _ = try self.sendRequest(method: "keybase.1.pgpUi.outputSignatureSuccessNonKeybase", args: args)
  }

  public func keyGenerated(kid: String, key: KeyInfo) throws {
    let args: [String: Any] = ["kid": kid, "key": key]
    _ = try self.sendRequest(method: "keybase.1.pgpUi.keyGenerated", args: args)
  }

  public func shouldPushPrivate() throws -> Bool {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.pgpUi.shouldPushPrivate", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func finished() throws {
    let args: [String: Any] = [String: Any]()
    _ = try self.sendRequest(method: "keybase.1.pgpUi.finished", args: args)
  }

}
