//
// This file is autogenerated
//

//
//  PgpUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// PgpUi
//

public class PgpUiRequest: Request {

  public func outputSignatureSuccess(fingerprint: String, username: String, signedAt: Int64) throws {
    let args: [String: AnyObject] = ["fingerprint": fingerprint, "username": username, "signedAt": NSNumber(longLong: signedAt)]
    try self.sendRequest("keybase.1.pgpUi.outputSignatureSuccess", args: args)
  }

}
