//
// This file is autogenerated
//

//
//  ProcessRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Process
//

public class ProcessRequest: Request {

}
