//
// This file is autogenerated
//

//
//  ProvisionUI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProvisionUI
//

public enum ProvisionMethod: Int {
	case device = 0
	case paperKey = 1
	case passphrase = 2
	case gpgImport = 3
	case gpgSign = 4
}

public enum GPGMethod: Int {
	case gpgNone = 0
	case gpgImport = 1
	case gpgSign = 2
}

public enum ChooseType: Int {
	case existingDevice = 0
	case newDevice = 1
}


public class SecretResponse {

	public let secret: NSData?
	public let phrase: String?

  public init(secret: NSData, phrase: String) {
    self.secret = secret
		self.phrase = phrase
  }

  public class func fromJSON(_ json: JSON) -> SecretResponse {
    return SecretResponse(secret: json["secret"].object as! NSData, phrase: json["phrase"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [SecretResponse] {
    return json.map { fromJSON($0) }
  }

}

