//
// This file is autogenerated
//

//
//  ProveCommon.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProveCommon
//

public enum ProofState: Int {
	case none = 0
	case ok = 1
	case tempFailure = 2
	case permFailure = 3
	case looking = 4
	case superseded = 5
	case posted = 6
	case revoked = 7
	case deleted = 8
}

public enum ProofStatus: Int {
	case none = 0
	case ok = 1
	case local = 2
	case found = 3
	case baseError = 100
	case hostUnreachable = 101
	case permissionDenied = 103
	case failedParse = 106
	case dnsError = 107
	case authFailed = 108
	case http429 = 129
	case http500 = 150
	case timeout = 160
	case internalError = 170
	case baseHardError = 200
	case notFound = 201
	case contentFailure = 202
	case badUsername = 203
	case badRemoteId = 204
	case textNotFound = 205
	case badArgs = 206
	case contentMissing = 207
	case titleNotFound = 208
	case serviceError = 209
	case torSkipped = 210
	case torIncompatible = 211
	case http300 = 230
	case http400 = 240
	case httpOther = 260
	case emptyJson = 270
	case deleted = 301
	case serviceDead = 302
	case badSignature = 303
	case badApiUrl = 304
	case unknownType = 305
	case noHint = 306
	case badHintText = 307
	case invalidPvl = 308
}

public enum ProofType: Int {
	case none = 0
	case keybase = 1
	case twitter = 2
	case github = 3
	case reddit = 4
	case coinbase = 5
	case hackernews = 6
	case facebook = 8
	case genericWebSite = 1000
	case dns = 1001
	case pgp = 1002
	case rooter = 100001
}
