//
// This file is autogenerated
//

//
//  ProveUI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProveUI
//

public enum PromptOverwriteType: Int {
	case social = 0
	case site = 1
}
