//
// This file is autogenerated
//

//
//  ProveRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Prove
//

public class ProveRequest: Request {

  public func startProof(service: String, username: String, force: Bool, promptPosted: Bool) throws -> StartProofResult {
    let args: [String: AnyObject] = ["service": service, "username": username, "force": force, "promptPosted": promptPosted]
    let response = try self.sendRequest("keybase.1.prove.startProof", args: args)
    try checkNull(response)
    return StartProofResult.fromJSON(JSON(response))
  }

  public func checkProof(sigID: String) throws -> CheckProofStatus {
    let args: [String: AnyObject] = ["sigID": sigID]
    let response = try self.sendRequest("keybase.1.prove.checkProof", args: args)
    try checkNull(response)
    return CheckProofStatus.fromJSON(JSON(response))
  }

}
