//
// This file is autogenerated
//

//
//  ProveCommonRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProveCommon
//

public class ProveCommonRequest: Request {

}
