//
// This file is autogenerated
//

//
//  ProveUi.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProveUi
//

public enum PromptOverwriteType: Int {
	case Social = 0
	case Site = 1
}
