//
// This file is autogenerated
//

//
//  ProveUIRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// ProveUI
//

public class ProveUIRequest: Request {

  public func promptOverwrite(account: String, typ: PromptOverwriteType) throws -> Bool {
    let args: [String: Any] = ["account": account, "typ": typ.rawValue]
    let response = try self.sendRequest(method: "keybase.1.proveUi.promptOverwrite", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func promptUsername(prompt: String, prevError: Status?) throws -> String {
    let args: [String: Any] = ["prompt": prompt, "prevError": wrapNull(prevError)]
    let response = try self.sendRequest(method: "keybase.1.proveUi.promptUsername", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

  public func outputPrechecks(text: Text) throws {
    let args: [String: Any] = ["text": text]
    _ = try self.sendRequest(method: "keybase.1.proveUi.outputPrechecks", args: args)
  }

  public func preProofWarning(text: Text) throws -> Bool {
    let args: [String: Any] = ["text": text]
    let response = try self.sendRequest(method: "keybase.1.proveUi.preProofWarning", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func outputInstructions(instructions: Text, proof: String) throws {
    let args: [String: Any] = ["instructions": instructions, "proof": proof]
    _ = try self.sendRequest(method: "keybase.1.proveUi.outputInstructions", args: args)
  }

  public func okToCheck(name: String, attempt: Int) throws -> Bool {
    let args: [String: Any] = ["name": name, "attempt": NSNumber(value: attempt)]
    let response = try self.sendRequest(method: "keybase.1.proveUi.okToCheck", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

  public func displayRecheckWarning(text: Text) throws {
    let args: [String: Any] = ["text": text]
    _ = try self.sendRequest(method: "keybase.1.proveUi.displayRecheckWarning", args: args)
  }

}
