//
// This file is autogenerated
//

//
//  Quota.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Quota
//


public class VerifySessionRes {

	public let uid: String
	public let sid: String
	public let generated: Int
	public let lifetime: Int

  public init(uid: String, sid: String, generated: Int, lifetime: Int) {
    self.uid = uid
		self.sid = sid
		self.generated = generated
		self.lifetime = lifetime
  }

  public class func fromJSON(json: JSON) -> VerifySessionRes {
    return VerifySessionRes(uid: json["uid"].stringValue, sid: json["sid"].stringValue, generated: json["generated"].intValue, lifetime: json["lifetime"].intValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [VerifySessionRes] {
    return json.map { fromJSON($0) }
  }
}
