//
// This file is autogenerated
//

//
//  QuotaRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Quota
//

public class QuotaRequest: Request {

  public func verifySession(session: String) throws -> VerifySessionRes {
    let args: [String: AnyObject] = ["session": session]
    let response = try self.sendRequest("keybase.1.quota.verifySession", args: args)
    try checkNull(response)
    return VerifySessionRes.fromJSON(JSON(response))
  }

}
