//
// This file is autogenerated
//

//
//  QuotaRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Quota
//

public class QuotaRequest: Request {

  public func verifySession(session: String) throws -> VerifySessionRes {
    let args: [String: Any] = ["session": session]
    let response = try self.sendRequest(method: "keybase.1.quota.verifySession", args: args)
    try checkNull(response: response)
    return VerifySessionRes.fromJSON(JSON(response))
  }

}
