//
// This file is autogenerated
//

//
//  RekeyUI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// RekeyUI
//

public enum RekeyEventType: Int {
	case none = 0
	case notLoggedIn = 1
	case apiError = 2
	case noProblems = 3
	case loadMeError = 4
	case currentDeviceCanRekey = 5
	case deviceLoadError = 6
	case harass = 7
	case noGregorMessages = 8
}


public class RekeyEvent {

	public let eventType: RekeyEventType?
	public let interruptType: Int?

  public init(eventType: RekeyEventType, interruptType: Int) {
    self.eventType = eventType
		self.interruptType = interruptType
  }

  public class func fromJSON(_ json: JSON) -> RekeyEvent {
    return RekeyEvent(eventType: RekeyEventType(rawValue: json["eventType"].intValue)!, interruptType: json["interruptType"].intValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [RekeyEvent] {
    return json.map { fromJSON($0) }
  }

}

