//
// This file is autogenerated
//

//
//  SaltpackUi.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SaltpackUi
//

public enum SaltpackSenderType: Int {
	case NotTracked = 0
	case Unknown = 1
	case Anonymous = 2
	case TrackingBroke = 3
	case TrackingOk = 4
	case VSelf = 5
}


public class SaltpackSender {

	public let uid: String
	public let username: String
	public let senderType: SaltpackSenderType

  public init(uid: String, username: String, senderType: SaltpackSenderType) {
    self.uid = uid
		self.username = username
		self.senderType = senderType
  }

  public class func fromJSON(json: JSON) -> SaltpackSender {
    return SaltpackSender(uid: json["uid"].stringValue, username: json["username"].stringValue, senderType: SaltpackSenderType(rawValue: json["senderType"].intValue)!)
  }

  public class func fromJSONArray(json: [JSON]) -> [SaltpackSender] {
    return json.map { fromJSON($0) }
  }
}
