//
// This file is autogenerated
//

//
//  SaltpackUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SaltpackUi
//

public class SaltpackUiRequest: Request {

  public func saltpackPromptForDecrypt(sender: SaltpackSender) throws {
    let args: [String: AnyObject] = ["sender": sender]
    try self.sendRequest("keybase.1.saltpackUi.saltpackPromptForDecrypt", args: args)
  }

  public func saltpackVerifySuccess(signingKID: String, sender: SaltpackSender) throws {
    let args: [String: AnyObject] = ["signingKID": signingKID, "sender": sender]
    try self.sendRequest("keybase.1.saltpackUi.saltpackVerifySuccess", args: args)
  }

}
