//
// This file is autogenerated
//

//
//  SaltpackUI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SaltpackUI
//

public enum SaltpackSenderType: Int {
	case notTracked = 0
	case unknown = 1
	case anonymous = 2
	case trackingBroke = 3
	case trackingOk = 4
	case selfValue = 5
}


public class SaltpackSender {

	public let uid: String?
	public let username: String?
	public let senderType: SaltpackSenderType?

  public init(uid: String, username: String, senderType: SaltpackSenderType) {
    self.uid = uid
		self.username = username
		self.senderType = senderType
  }

  public class func fromJSON(_ json: JSON) -> SaltpackSender {
    return SaltpackSender(uid: json["uid"].stringValue, username: json["username"].stringValue, senderType: SaltpackSenderType(rawValue: json["senderType"].intValue)!)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [SaltpackSender] {
    return json.map { fromJSON($0) }
  }

}

