//
// This file is autogenerated
//

//
//  SecretKeys.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SecretKeys
//

public typealias NaclSigningKeyPublic = [UInt8] // Size: 32
public typealias NaclSigningKeyPrivate = [UInt8] // Size: 64
public typealias NaclDHKeyPublic = [UInt8] // Size: 32
public typealias NaclDHKeyPrivate = [UInt8] // Size: 32

public class SecretKeys {

	public let signing: NSData?
	public let encryption: NSData?

  public init(signing: NSData, encryption: NSData) {
    self.signing = signing
		self.encryption = encryption
  }

  public class func fromJSON(_ json: JSON) -> SecretKeys {
    return SecretKeys(signing: json["signing"].object as! NSData, encryption: json["encryption"].object as! NSData)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [SecretKeys] {
    return json.map { fromJSON($0) }
  }

}

