//
// This file is autogenerated
//

//
//  SecretUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SecretUi
//

public class SecretUiRequest: Request {

  public func getPassphrase(pinentry: GUIEntryArg, terminal: SecretEntryArg?) throws -> GetPassphraseRes {
    let args: [String: AnyObject] = ["pinentry": pinentry, "terminal": wrapNull(terminal)]
    let response = try self.sendRequest("keybase.1.secretUi.getPassphrase", args: args)
    try checkNull(response)
    return GetPassphraseRes.fromJSON(JSON(response))
  }

}
