//
// This file is autogenerated
//

//
//  SecretKeysRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// SecretKeys
//

public class SecretKeysRequest: Request {

  public func getSecretKeys() throws -> SecretKeys {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.SecretKeys.getSecretKeys", args: args)
    try checkNull(response)
    return SecretKeys.fromJSON(JSON(response))
  }

}
