//
// This file is autogenerated
//

//
//  SessionRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Session
//

public class SessionRequest: Request {

  public func currentSession() throws -> Session {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.session.currentSession", args: args)
    try checkNull(response)
    return Session.fromJSON(JSON(response))
  }

}
