//
// This file is autogenerated
//

//
//  SessionRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Session
//

public class SessionRequest: Request {

  public func currentSession() throws -> Session {
    let args: [String: Any] = [String: Any]()
    let response = try self.sendRequest(method: "keybase.1.session.currentSession", args: args)
    try checkNull(response: response)
    return Session.fromJSON(JSON(response))
  }

  public func sessionPing() throws {
    let args: [String: Any] = [String: Any]()
    _ = try self.sendRequest(method: "keybase.1.session.sessionPing", args: args)
  }

}
