//
// This file is autogenerated
//

//
//  SignupRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Signup
//

public class SignupRequest: Request {

  public func checkUsernameAvailable(username: String) throws {
    let args: [String: AnyObject] = ["username": username]
    try self.sendRequest("keybase.1.signup.checkUsernameAvailable", args: args)
  }

  public func signup(email: String, inviteCode: String, passphrase: String, username: String, deviceName: String, storeSecret: Bool, skipMail: Bool) throws -> SignupRes {
    let args: [String: AnyObject] = ["email": email, "inviteCode": inviteCode, "passphrase": passphrase, "username": username, "deviceName": deviceName, "storeSecret": storeSecret, "skipMail": skipMail]
    let response = try self.sendRequest("keybase.1.signup.signup", args: args)
    try checkNull(response)
    return SignupRes.fromJSON(JSON(response))
  }

  public func inviteRequest(email: String, fullname: String, notes: String) throws {
    let args: [String: AnyObject] = ["email": email, "fullname": fullname, "notes": notes]
    try self.sendRequest("keybase.1.signup.inviteRequest", args: args)
  }

  public func checkInvitationCode(invitationCode: String) throws {
    let args: [String: AnyObject] = ["invitationCode": invitationCode]
    try self.sendRequest("keybase.1.signup.checkInvitationCode", args: args)
  }

}
