//
// This file is autogenerated
//

//
//  Signup.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Signup
//


public class SignupRes {

	public let passphraseOk: Bool
	public let postOk: Bool
	public let writeOk: Bool

  public init(passphraseOk: Bool, postOk: Bool, writeOk: Bool) {
    self.passphraseOk = passphraseOk
		self.postOk = postOk
		self.writeOk = writeOk
  }

  public class func fromJSON(json: JSON) -> SignupRes {
    return SignupRes(passphraseOk: json["passphraseOk"].boolValue, postOk: json["postOk"].boolValue, writeOk: json["writeOk"].boolValue)
  }

  public class func fromJSONArray(json: [JSON]) -> [SignupRes] {
    return json.map { fromJSON($0) }
  }
}
