//
// This file is autogenerated
//

//
//  SigsRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Sigs
//

public class SigsRequest: Request {

  public func sigList(arg: SigListArgs) throws -> [Sig] {
    let args: [String: Any] = ["arg": arg]
    let response = try self.sendRequest(method: "keybase.1.sigs.sigList", args: args)
  try checkNull(response: response)
  return Sig.fromJSONArray(JSON(response).arrayValue)
  }

  public func sigListJSON(arg: SigListArgs) throws -> String {
    let args: [String: Any] = ["arg": arg]
    let response = try self.sendRequest(method: "keybase.1.sigs.sigListJSON", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

}
