//
// This file is autogenerated
//

//
//  StreamUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// StreamUi
//

public class StreamUiRequest: Request {

  public func close(s: Stream) throws {
    let args: [String: AnyObject] = ["s": s]
    try self.sendRequest("keybase.1.streamUi.close", args: args)
  }

  public func read(s: Stream, sz: Int) throws -> NSData {
    let args: [String: AnyObject] = ["s": s, "sz": NSNumber(integer: sz)]
    let response = try self.sendRequest("keybase.1.streamUi.read", args: args)
    try checkNull(response)
    return JSON(response).object as! NSData
  }

  public func write(s: Stream, buf: NSData) throws -> Int {
    let args: [String: AnyObject] = ["s": s, "buf": buf]
    let response = try self.sendRequest("keybase.1.streamUi.write", args: args)
    try checkNull(response)
    return JSON(response).intValue
  }

}
