//
// This file is autogenerated
//

//
//  Test.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Test
//


public class Test {

	public let reply: String?

  public init(reply: String) {
    self.reply = reply
  }

  public class func fromJSON(_ json: JSON) -> Test {
    return Test(reply: json["reply"].stringValue)
  }

  public class func fromJSONArray(_ json: [JSON]) -> [Test] {
    return json.map { fromJSON($0) }
  }

}

