//
// This file is autogenerated
//

//
//  TestRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Test
//

public class TestRequest: Request {

/*!
 Call test method.
 Will trigger the testCallback method, whose result will be set in the
 returned Test object, reply property.
 */
  public func test(name: String) throws -> Test {
    let args: [String: Any] = ["name": name]
    let response = try self.sendRequest(method: "keybase.1.test.test", args: args)
    try checkNull(response: response)
    return Test.fromJSON(JSON(response))
  }

/*!
 This is a service callback triggered from test(..).
 The name param is what was passed into test.
 */
  public func testCallback(name: String) throws -> String {
    let args: [String: Any] = ["name": name]
    let response = try self.sendRequest(method: "keybase.1.test.testCallback", args: args)
    try checkNull(response: response)
    return JSON(response).stringValue
  }

/*!
 For testing crashes.
 */
  public func panic(message: String) throws {
    let args: [String: Any] = ["message": message]
    _ = try self.sendRequest(method: "keybase.1.test.panic", args: args)
  }

}
