//
// This file is autogenerated
//

//
//  TrackRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Track
//

public class TrackRequest: Request {

/*!
 This will perform identify and track.
 If forceRemoteCheck is true, we force all remote proofs to be checked
 (otherwise a cache is used).
 */
  public func track(userAssertion: String, options: TrackOptions, forceRemoteCheck: Bool) throws {
    let args: [String: AnyObject] = ["userAssertion": userAssertion, "options": options, "forceRemoteCheck": forceRemoteCheck]
    try self.sendRequest("keybase.1.track.track", args: args)
  }

/*!
 Track with token returned from identify.
 */
  public func trackWithToken(trackToken: String, options: TrackOptions) throws {
    let args: [String: AnyObject] = ["trackToken": trackToken, "options": options]
    try self.sendRequest("keybase.1.track.trackWithToken", args: args)
  }

  public func untrack(username: String) throws {
    let args: [String: AnyObject] = ["username": username]
    try self.sendRequest("keybase.1.track.untrack", args: args)
  }

  public func checkTracking() throws {
    let args: [String: AnyObject] = [String: AnyObject]()
    try self.sendRequest("keybase.1.track.checkTracking", args: args)
  }

  public func fakeTrackingChanged(username: String) throws {
    let args: [String: AnyObject] = ["username": username]
    try self.sendRequest("keybase.1.track.fakeTrackingChanged", args: args)
  }

}
