//
// This file is autogenerated
//

//
//  Ui.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Ui
//

public enum PromptDefault: Int {
	case None = 0
	case Yes = 1
	case No = 2
}
