//
// This file is autogenerated
//

//
//  UI.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// UI
//

public enum PromptDefault: Int {
	case none = 0
	case yes = 1
	case no = 2
}
