//
// This file is autogenerated
//

//
//  UiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// Ui
//

public class UiRequest: Request {

  public func promptYesNo(text: Text, promptDefault: PromptDefault) throws -> Bool {
    let args: [String: AnyObject] = ["text": text, "promptDefault": promptDefault.rawValue]
    let response = try self.sendRequest("keybase.1.ui.promptYesNo", args: args)
    try checkNull(response)
    return JSON(response).boolValue
  }

}
