//
// This file is autogenerated
//

//
//  UIRequest.swift
//  Keybase
//  Copyright © 2016 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// UI
//

public class UIRequest: Request {

  public func promptYesNo(text: Text, promptDefault: PromptDefault) throws -> Bool {
    let args: [String: Any] = ["text": text, "promptDefault": promptDefault.rawValue]
    let response = try self.sendRequest(method: "keybase.1.ui.promptYesNo", args: args)
    try checkNull(response: response)
    return JSON(response).boolValue
  }

}
