//
// This file is autogenerated
//

//
//  UpdateUiRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// UpdateUi
//

public class UpdateUiRequest: Request {

  public func updatePrompt(update: Update, options: UpdatePromptOptions) throws -> UpdatePromptRes {
    let args: [String: AnyObject] = ["update": update, "options": options]
    let response = try self.sendRequest("keybase.1.updateUi.updatePrompt", args: args)
    try checkNull(response)
    return UpdatePromptRes.fromJSON(JSON(response))
  }

  public func updateAppInUse(update: Update, processes: [Process]) throws -> UpdateAppInUseRes {
    let args: [String: AnyObject] = ["update": update, "processes": processes]
    let response = try self.sendRequest("keybase.1.updateUi.updateAppInUse", args: args)
    try checkNull(response)
    return UpdateAppInUseRes.fromJSON(JSON(response))
  }

  public func updateQuit(update: Update, status: Status) throws -> UpdateQuitRes {
    let args: [String: AnyObject] = ["update": update, "status": status]
    let response = try self.sendRequest("keybase.1.updateUi.updateQuit", args: args)
    try checkNull(response)
    return UpdateQuitRes.fromJSON(JSON(response))
  }

}
