//
// This file is autogenerated
//

//
//  UserRequest.swift
//  Keybase
//  Copyright © 2015 Keybase. All rights reserved.
//

import Foundation
import SwiftyJSON



//
// User
//

public class UserRequest: Request {

  public func listTrackers(uid: String) throws -> [Tracker] {
    let args: [String: AnyObject] = ["uid": uid]
    let response = try self.sendRequest("keybase.1.user.listTrackers", args: args)
  try checkNull(response)
  return Tracker.fromJSONArray(JSON(response).arrayValue)
  }

  public func listTrackersByName(username: String) throws -> [Tracker] {
    let args: [String: AnyObject] = ["username": username]
    let response = try self.sendRequest("keybase.1.user.listTrackersByName", args: args)
  try checkNull(response)
  return Tracker.fromJSONArray(JSON(response).arrayValue)
  }

  public func listTrackersSelf() throws -> [Tracker] {
    let args: [String: AnyObject] = [String: AnyObject]()
    let response = try self.sendRequest("keybase.1.user.listTrackersSelf", args: args)
  try checkNull(response)
  return Tracker.fromJSONArray(JSON(response).arrayValue)
  }

/*!
 Load user summaries for the supplied uids.
 They are "unchecked" in that the client is not verifying the info from the server.
 If len(uids) > 500, the first 500 will be returned.
 */
  public func loadUncheckedUserSummaries(uids: [String]) throws -> [UserSummary] {
    let args: [String: AnyObject] = ["uids": uids]
    let response = try self.sendRequest("keybase.1.user.loadUncheckedUserSummaries", args: args)
  try checkNull(response)
  return UserSummary.fromJSONArray(JSON(response).arrayValue)
  }

/*!
 Load a user from the server.
 */
  public func loadUser(uid: String) throws -> User {
    let args: [String: AnyObject] = ["uid": uid]
    let response = try self.sendRequest("keybase.1.user.loadUser", args: args)
    try checkNull(response)
    return User.fromJSON(JSON(response))
  }

/*!
 Load a user + device keys from the server.
 */
  public func loadUserPlusKeys(uid: String) throws -> UserPlusKeys {
    let args: [String: AnyObject] = ["uid": uid]
    let response = try self.sendRequest("keybase.1.user.loadUserPlusKeys", args: args)
    try checkNull(response)
    return UserPlusKeys.fromJSON(JSON(response))
  }

/*!
 Load public keys for a user.
 */
  public func loadPublicKeys(uid: String) throws -> [PublicKey] {
    let args: [String: AnyObject] = ["uid": uid]
    let response = try self.sendRequest("keybase.1.user.loadPublicKeys", args: args)
  try checkNull(response)
  return PublicKey.fromJSONArray(JSON(response).arrayValue)
  }

/*!
 The list-tracking function get verified data from the tracking statements
 in the user's own sigchain.
 */
  public func listTracking(filter: String) throws -> [UserSummary] {
    let args: [String: AnyObject] = ["filter": filter]
    let response = try self.sendRequest("keybase.1.user.listTracking", args: args)
  try checkNull(response)
  return UserSummary.fromJSONArray(JSON(response).arrayValue)
  }

  public func listTrackingJSON(filter: String, verbose: Bool) throws -> String {
    let args: [String: AnyObject] = ["filter": filter, "verbose": verbose]
    let response = try self.sendRequest("keybase.1.user.listTrackingJSON", args: args)
    try checkNull(response)
    return JSON(response).stringValue
  }

/*!
 Search for users who match a given query.
 */
  public func search(query: String) throws -> [SearchResult] {
    let args: [String: AnyObject] = ["query": query]
    let response = try self.sendRequest("keybase.1.user.search", args: args)
  try checkNull(response)
  return SearchResult.fromJSONArray(JSON(response).arrayValue)
  }

}
